### ISSUE TITLE
Sugestão para inclusão de livro:  Data Science para Negócios

### ISSUE THREAD

**Issue by eliezerfb** [leportella/datascience-pizza#110]
Minha sugestão para adicionar este livro:

Data Science para Negócios: O que você precisa saber sobre mineração de dados e pensamento analítico de dados.

Anexo um capítulo de amostra.
[capitulo_de_amostra_Data_Science_Negócios.pdf](https://github.com/leportella/datascience-pizza/files/1383561/capitulo_de_amostra_Data_Science_Negocios.pdf)

**Comment by leportella** [comment]
@eliezerfb eu tenho esse livro e gosto muito. Tem interesse de fazer um pull request com a sua sugestão? Se precisar de ajuda, só falar!
