### ISSUE TITLE
Inclusão de meetups e eventos

### ISSUE THREAD

**Issue by cleisonsilfer** [leportella/datascience-pizza#124]
Atualmente, existe a seção de "Grupos" voltado para facebook e telegram.
Acho que seria interessante termos uma seção para divulgação de Meetups e eventos de Datascience.

**Comment by eliezerfb** [comment]
Também acredito ser interessante.
Como sugestão, não sei se seria viável, utilizar o Google Agenda e fazer uma agenda pública e adicionar o link aqui?

**Comment by GustavoSFCoelho** [comment]
talvez utilizar um api do meetup tipo o que eles tem no pydata (não sei se
é viável) https://www.meetup.com/pt-BR/pro/pydata/, agora olhando melhor
deve ser pago.

2017-10-25 13:32 GMT-02:00 Eliézer F. Bourchardt <notifications@github.com>:

**Comment by cleisonsilfer** [comment]
Eu estava pensando em criar um arquivo e listar os meetups por estado. Não tinha pensando em chegar a esse nível de criar uma agenda. Mas é algo bem interessante

**Comment by eliezerfb** [comment]
Olha, acredito que dê pra começar com um arquivo listando por estado sim, depois a gente vê se é interessante colocar em uma agenda ou não. 
A vantagem de separar por estado é que fica fácil de achar algo que esteja acontecendo perto.

**Comment by mvinoba** [comment]
Um `topicos/meetups-e-eventos.md` organizado por estados seria bem interessante. 
Eu posso criar e ajudar a manter um do Rio, mas além dos eventos que os organizadores anunciam no meetup.com eu conheço poucos outros. Parece que a próxima PythonRio será com tema de Data Science, e a EMAp da FGV costuma ter algumas palestras também.
