### ISSUE TITLE
Criar documento para ajudar quem quiser contribuir 

### ISSUE THREAD

**Issue by leportella** [leportella/datascience-pizza#283]

**Comment by LTKills** [comment]
Você tem em mente padrões para contribuir ou isso também é parte do issue?

**Comment by leportella** [comment]
Alguns padrões que eu sei:

* Nome do PR tem que ser descritivo do que ele faz
* Todo material do dicionário tem que ter referência, seja link ou referência bibliográfica
* Se o item for um material em portugues, colocar uma tag conforme definido do #284 
* Colocar o nome num doc de contribuição

**Comment by leportella** [comment]
Opa!! Esqueci que [já tem um documento](https://github.com/leportella/datascience-pizza/blob/master/contribuindo.md)

Acho que tem que melhorar só hehehehe

**Comment by leportella** [comment]
fechado! Obrigada @LTKills
