### ISSUE TITLE
Conferir se todo material em PT tem um label avisando que o material está disponível em PT

### ISSUE THREAD

**Issue by leportella** [leportella/datascience-pizza#284]

**Comment by LTKills** [comment]
Posso pegar esse? Qual é o formato dessa label? Apenas textual ou é em markdown?

**Comment by leportella** [comment]
@LTKills  pode pegar sim! [Nesse link](https://github.com/leportella/datascience-pizza/blob/master/topicos/cursos.md) tem um exemplo de como colocar a tag. Mas seria legal que fosse sempre no começo do texto. Assim:

* **[pt]** Curso de Aprendizado de Máquina ...

**Comment by LTKills** [comment]
Dei uma olhada e parece que tem umas inconsistências. Só para esclarecer, o formato é Curso de... **[pt-br]**, Curso... **[pt]**, **[pt]** Curso... ou **[pt-br]** Curso...?

**Comment by LTKills** [comment]
Estou usando o seguinte

Curso de data science | [**pt-br**]

**Comment by leportella** [comment]
vou fechar :)
