### ISSUE TITLE
Incluir definição de Support Vector Machine no dicionário

### ISSUE THREAD

**Issue by leportella** [leportella/datascience-pizza#48]
Recomenda-se a inclusão de artigos e fontes de consulta de onde as definições foram retiradas.

**Comment by GustavoSFCoelho** [comment]
Quem quiser escrever a definição tem esse ótimo vídeo https://www.youtube.com/watch?v=lYJ96LGZ_2E em que o Brandon Rohrer explica como estudar algoritmos pra entender oq eles fazem e ele usca SVM como exemplo. Quero resolver essa issue em breve, mas deixo o link caso alguém queria atacar antes.

**Comment by leportella** [comment]
@GustavoSFCoelho muito legal esse material. Será que seria o caso de fazermos documentos específicos para esse tipo de material?
