### ISSUE TITLE
Incluir definição de Perceptron no dicionário

### ISSUE THREAD

**Issue by leportella** [leportella/datascience-pizza#53]
Recomenda-se a inclusão de artigos e fontes de consulta de onde as definições foram retiradas.

**Comment by rgiovanini** [comment]
Opa! Deixa essa comigo!

**Comment by diogoffmelo** [comment]
Olá @rgiovanini, ainda pretendes trabalhar nessa issue?

**Comment by rgiovanini** [comment]
Olá, @diogoffmelo. Pretendo, mas tive um contratempo e vou ter que adiar uns dias. Você quer se encarregar?
