### ISSUE TITLE
Item no dicionário poderia ser "linkável"

### ISSUE THREAD

**Issue by arthur-gouveia** [leportella/datascience-pizza#81]
Atualmente o arquivo dicionário.md tem a seguinte estrutura:

# A
**Algoritmos**: São conjuntos de ...

Sugiro uma estrutura do tipo

# A
 ## Algoritmos
São conjuntos de ...

Colocando os items em um header (H2 ou H3) seria possível linkar uma definição com a outra. Por exemplo, na definição de Quartil que eu fiz eu gostaria de linkar com a definição de Mediana mas não consigo...

Se quiser eu posso fazer essas alterações e enviar um PR.

**Comment by giovanisleite** [comment]
O estilo pode ser mantido e utilizarmos a propriedade `name` dos links.

```
<a name="algoritmos">Algoritmos</a>
```
Exemplo:
<a name="algoritmos">Algoritmos</a> são Haxx0r ipsum pwned socket interpreter private all your base are belong to us cd win afk spoof memory leak recursively. Linux ack gnu ascii lib piggyback Donald Knuth concurrently. Kilo break pragma endif bar fopen Trojan horse script kiddies grep ifdef Linus Torvalds highjack.
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
[link para algoritmos](#algoritmos)

**Comment by leportella** [comment]
Gostei da ideia! Vou colocar uma label de `help wanted` para fazer isso, o que acham?

**Comment by mvinoba** [comment]
Tenho interesse em ajudar com a formatação do arquivo, acho que usar um header (talvez H3) seja melhor que usar a propriedade `name` porque evidencia a possibilidade de linkação externa pros leitores.
